name: build
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'check'
            python: '3.11'
            toxpython: 'python3.11'
            tox_env: 'check'
            os: 'ubuntu-latest'
          - name: 'docs'
            python: '3.11'
            toxpython: 'python3.11'
            tox_env: 'docs'
            os: 'ubuntu-latest'
          - name: 'py38-pg2 (ubuntu)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-pg2'
            os: 'ubuntu-latest'
          - name: 'py38-pg2 (macos)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-pg2'
            os: 'macos-latest'
          - name: 'py38-pg3 (ubuntu)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-pg3'
            os: 'ubuntu-latest'
          - name: 'py38-pg3 (macos)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-pg3'
            os: 'macos-latest'
          - name: 'py39-pg2 (ubuntu)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-pg2'
            os: 'ubuntu-latest'
          - name: 'py39-pg2 (macos)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-pg2'
            os: 'macos-latest'
          - name: 'py39-pg3 (ubuntu)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-pg3'
            os: 'ubuntu-latest'
          - name: 'py39-pg3 (macos)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-pg3'
            os: 'macos-latest'
          - name: 'py310-pg2 (ubuntu)'
            python: '3.10'
            toxpython: 'python3.10'
            python_arch: 'x64'
            tox_env: 'py310-pg2'
            os: 'ubuntu-latest'
          - name: 'py310-pg2 (macos)'
            python: '3.10'
            toxpython: 'python3.10'
            python_arch: 'x64'
            tox_env: 'py310-pg2'
            os: 'macos-latest'
          - name: 'py310-pg3 (ubuntu)'
            python: '3.10'
            toxpython: 'python3.10'
            python_arch: 'x64'
            tox_env: 'py310-pg3'
            os: 'ubuntu-latest'
          - name: 'py310-pg3 (macos)'
            python: '3.10'
            toxpython: 'python3.10'
            python_arch: 'x64'
            tox_env: 'py310-pg3'
            os: 'macos-latest'
          - name: 'py311-pg2 (ubuntu)'
            python: '3.11'
            toxpython: 'python3.11'
            python_arch: 'x64'
            tox_env: 'py311-pg2'
            os: 'ubuntu-latest'
          - name: 'py311-pg2 (macos)'
            python: '3.11'
            toxpython: 'python3.11'
            python_arch: 'x64'
            tox_env: 'py311-pg2'
            os: 'macos-latest'
          - name: 'py311-pg3 (ubuntu)'
            python: '3.11'
            toxpython: 'python3.11'
            python_arch: 'x64'
            tox_env: 'py311-pg3'
            os: 'ubuntu-latest'
          - name: 'py311-pg3 (macos)'
            python: '3.11'
            toxpython: 'python3.11'
            python_arch: 'x64'
            tox_env: 'py311-pg3'
            os: 'macos-latest'
          - name: 'py312-pg2 (ubuntu)'
            python: '3.12'
            toxpython: 'python3.12'
            python_arch: 'x64'
            tox_env: 'py312-pg2'
            os: 'ubuntu-latest'
          - name: 'py312-pg2 (macos)'
            python: '3.12'
            toxpython: 'python3.12'
            python_arch: 'x64'
            tox_env: 'py312-pg2'
            os: 'macos-latest'
          - name: 'py312-pg3 (ubuntu)'
            python: '3.12'
            toxpython: 'python3.12'
            python_arch: 'x64'
            tox_env: 'py312-pg3'
            os: 'ubuntu-latest'
          - name: 'py312-pg3 (macos)'
            python: '3.12'
            toxpython: 'python3.12'
            python_arch: 'x64'
            tox_env: 'py312-pg3'
            os: 'macos-latest'
          - name: 'pypy38-pg2 (ubuntu)'
            python: 'pypy-3.8'
            toxpython: 'pypy3.8'
            python_arch: 'x64'
            tox_env: 'pypy38-pg2'
            os: 'ubuntu-latest'
          - name: 'pypy38-pg2 (macos)'
            python: 'pypy-3.8'
            toxpython: 'pypy3.8'
            python_arch: 'x64'
            tox_env: 'pypy38-pg2'
            os: 'macos-latest'
          - name: 'pypy38-pg3 (ubuntu)'
            python: 'pypy-3.8'
            toxpython: 'pypy3.8'
            python_arch: 'x64'
            tox_env: 'pypy38-pg3'
            os: 'ubuntu-latest'
          - name: 'pypy38-pg3 (macos)'
            python: 'pypy-3.8'
            toxpython: 'pypy3.8'
            python_arch: 'x64'
            tox_env: 'pypy38-pg3'
            os: 'macos-latest'
          - name: 'pypy39-pg2 (ubuntu)'
            python: 'pypy-3.9'
            toxpython: 'pypy3.9'
            python_arch: 'x64'
            tox_env: 'pypy39-pg2'
            os: 'ubuntu-latest'
          - name: 'pypy39-pg2 (macos)'
            python: 'pypy-3.9'
            toxpython: 'pypy3.9'
            python_arch: 'x64'
            tox_env: 'pypy39-pg2'
            os: 'macos-latest'
          - name: 'pypy39-pg3 (ubuntu)'
            python: 'pypy-3.9'
            toxpython: 'pypy3.9'
            python_arch: 'x64'
            tox_env: 'pypy39-pg3'
            os: 'ubuntu-latest'
          - name: 'pypy39-pg3 (macos)'
            python: 'pypy-3.9'
            toxpython: 'pypy3.9'
            python_arch: 'x64'
            tox_env: 'pypy39-pg3'
            os: 'macos-latest'
          - name: 'pypy310-pg2 (ubuntu)'
            python: 'pypy-3.10'
            toxpython: 'pypy3.10'
            python_arch: 'x64'
            tox_env: 'pypy310-pg2'
            os: 'ubuntu-latest'
          - name: 'pypy310-pg2 (macos)'
            python: 'pypy-3.10'
            toxpython: 'pypy3.10'
            python_arch: 'x64'
            tox_env: 'pypy310-pg2'
            os: 'macos-latest'
          - name: 'pypy310-pg3 (ubuntu)'
            python: 'pypy-3.10'
            toxpython: 'pypy3.10'
            python_arch: 'x64'
            tox_env: 'pypy310-pg3'
            os: 'ubuntu-latest'
          - name: 'pypy310-pg3 (macos)'
            python: 'pypy-3.10'
            toxpython: 'pypy3.10'
            python_arch: 'x64'
            tox_env: 'pypy310-pg3'
            os: 'macos-latest'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.python_arch }}
    - name: install dependencies
      run: |
        python -mpip install --progress-bar=off -r ci/requirements.txt
        virtualenv --version
        pip --version
        tox --version
        pip list --format=freeze
    - name: test
      env:
        TOXPYTHON: '${{ matrix.toxpython }}'
      run: >
        tox -e ${{ matrix.tox_env }} -v
  finish:
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true
